#
# Module manifest for module 'PSKeepAChangelogTools'
#
# Generated by: takatoshi
#
# Generated on: 2026-05-17
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'PSKeepAChangelogTools.psm1'

    # Version number of this module.
    ModuleVersion = '0.1.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core', 'Desktop')

    # ID used to uniquely identify this module
    GUID = 'b90e468d-788a-40a5-b06f-12c527599efe'

    # Author of this module
    Author = 'Takatoshi Kuriyama'

    # Copyright statement for this module
    Copyright = 'Copyright © 2026 Takatoshi Kuriyama. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'A PowerShell module for parsing, validating, and synchronizing Keep a Changelog style changelogs.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Get-KeepAChangelogSection'
        'Get-KeepAChangelogEntry'
        'Assert-KeepAChangelogReleaseMetadata'
        'Get-KeepAChangelogManifestReleaseNotes'
        'Set-KeepAChangelogManifestReleaseNotes'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Changelog', 'KeepAChangelog', 'ReleaseNotes', 'Automation', 'PowerShell', 'CI')

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/krymtkts/PSKeepAChangelogTools/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/krymtkts/PSKeepAChangelogTools'

            # ReleaseNotes of this module

            ReleaseNotes = @'
## [0.1.0]

### Added

- Add `Get-KeepAChangelogSection` for reading changelog sections by version.
- Add `Get-KeepAChangelogEntry` for reading rendered changelog entries by version.
- Add `Assert-KeepAChangelogReleaseMetadata` for validating changelog versions and release tags.
- Add `Get-KeepAChangelogManifestReleaseNotes` for rendering manifest release notes from `CHANGELOG.md`.
- Add `Set-KeepAChangelogManifestReleaseNotes` for updating manifest release notes.
- Add build tasks for linting, tests, and release note synchronization.
- Add staged-module integration tests, CI, and release automation.

### Notes

- This is the first public release of `PSKeepAChangelogTools`.
- Supported PowerShell versions are Windows PowerShell 5.1 through PowerShell 7.x.
- The module scope is intentionally limited to Keep a Changelog style changelogs.

Full CHANGELOG: https://github.com/krymtkts/PSKeepAChangelogTools/blob/main/CHANGELOG.md
'@

            # Prerelease string of this module
            # Prerelease = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
